# Generated by Django 2.2.1 on 2019-06-04 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my', '0004_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
