# Generated by Django 2.2.1 on 2019-06-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my', '0005_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='image',
            field=models.ImageField(default='', upload_to='my/images/'),
        ),
    ]
